<a href="https://colab.research.google.com/github/dc-dzekochris/regression-in-ML/blob/main/regressionmachinelearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##regression machine learning
it is a supervised learning technique because the dataset used contain some  Features and Outcomes(Label). Regression focuses on predicting labels that are Numerical in Nature e,g Sales Prediction...

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT08q-AvBSEJHKH-CqwgSzVXz7EpN0mntIFfQ&s">

In [38]:
#sales prediction based on advertising
#importing pandas libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [39]:
#reading dataset
sales_data=pd.read_csv('https://msi.martial.co.ke/data/Advertising.csv')
sales_data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [40]:
#data analysis
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


In [41]:
sales_data.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [42]:
sales_data.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [43]:
#correlation analysis
sales_data.corr()

TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.782224
Radio      0.054809  1.000000   0.354104  0.576223
Newspaper  0.056648  0.354104   1.000000  0.228299
Sales      0.782224  0.576223   0.228299  1.000000

In [44]:
#machine learning
#step 1: divide dataset into features(x) and label(y)
#convert sales dataset into numpy array to extract values
array=sales_data.values
array
#x=features(tv,radio,newspaper)
#200 records and 3 columns
x=array[:,0:3]
x
print(x.shape)

y=array[:,3]
print(y.shape)

(200, 3)
(200,)


In [45]:
#step 2
#divide the x and y into training and testing
#x->x_train(70) and x_test(30)
#y->y-train(70) and y_test(30)

from sklearn import model_selection
x_train,x_test,y_train,y_test=model_selection.train_test_split(x,y,test_size=0.30,random_state=42)
print (x_train.shape,y_train.shape)
print (x_test.shape,y_test.shape)

(140, 3) (140,)
(60, 3) (60,)


In [46]:
#step 3
#import machine learning algorithm
#a. linear regression
from sklearn.linear_model import LinearRegression

#b. decision trees
from sklearn.tree import DecisionTreeRegressor

#c. k-nearest neighbor algorithm
from sklearn.neighbors import KNeighborsRegressor

#d. support vector machine
from sklearn.svm import SVR

#e. random forest
from sklearn.ensemble import RandomForestRegressor

#f. gradient boosting
from sklearn.ensemble import GradientBoostingRegressor

#g. adaboost
from sklearn.ensemble import AdaBoostRegressor



In [47]:
#step 4: cross validating
#process that is used to determine the best learning algorithm for the particular problem
# STEP4: CROSS VALIDATION
# Hyperparameter Tuning.
# Process that is used to Determine the Best Learning Algorithm for a Particular Problem.

In [48]:
#step 5: model training
#in this process, the models learnt from the training dataset using the best algorithm
model= DecisionTreeRegressor()
model.fit(x_train,y_train)

DecisionTreeRegressor()

In [49]:
#step 6: model evaluation
# process used to determine whether model is accurate to predict the results
#in regression(numbers), we use the Mean Absolute Error(mae)

model_predictions=model.predict(x_test)
model_predictions

array([18.5, 23.8, 17.6,  5.3, 23.8, 15.3, 22.6, 10.1, 12. , 16.6,  8.8,
        8.6, 11.7,  1.6, 10.3, 12.9,  5.3, 17.3,  9.7, 19.8, 17.6, 15.3,
       10.8, 23.8,  9.9,  8.7, 22.6, 12.2, 10.6,  4.8, 11.4, 10.1, 23.8,
        9.3, 15.9, 23.8, 10.4, 17.6, 12.4,  6.6, 11.6, 12.6, 10.4, 10.1,
       12. ,  8.6,  9.7, 15. ,  9.7, 11.8, 13.6, 12.6,  5.3,  5.3,  8.7,
       11.2,  9.9, 24.2,  6.6, 11.4])

In [50]:
y_test

array([16.9, 22.4, 21.4,  7.3, 24.7, 12.6, 22.3,  8.4, 11.5, 14.9,  9.5,
        8.7, 11.9,  5.3, 10.3, 11.7,  5.5, 16.6, 11.3, 18.9, 19.7, 12.5,
       10.9, 22.2,  9.3,  8.1, 21.7, 13.4, 10.6,  5.7, 10.6, 11.3, 23.7,
        8.7, 16.1, 20.7, 11.6, 20.8, 11.9,  6.9, 11. , 12.8, 10.1,  9.7,
       11.6,  7.6, 10.5, 14.6, 10.4, 12. , 14.6, 11.7,  7.2,  6.6,  9.4,
       11. , 10.9, 25.4,  7.6, 11.7])

In [55]:
#scientific model evaluation
#regression we use r2_score
#ration between the model_predictions and y_test
from sklearn.metrics import r2_score
r2_score(y_test,model_predictions)*100

93.05489641095383

In [54]:
#step 6: model prediction
#sales prediction for new data
#features=[300,50,120]
#outcome=model.predict(features)
#outcome
features = [[300, 50, 120]]
outcome = model.predict(features)
outcome

array([26.2])

In [ ]:
#research on:
#overfitting problem in ML
#underfitting problem in ML
#hyper parameter tuning
#feature emlimination